site_name: RadonMiner
repo_name: GitHub
repo_url: https://github.com/radon-h2020/radon-repository-miner/
nav:
    - Getting Started:
        - Quick Start: index.md
    - CLI Usage: cli.md
    - API Reference: apis.md
    - About: about.md
markdown_extensions:
  - admonition